//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCBOPayrollEmailGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WCBOPayrollEmailGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize {
            get {
                object obj = ResourceManager.GetObject("minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2/18/2022
        ///3/4/2022
        ///3/18/2022
        ///4/1/2022
        ///4/15/2022
        ///4/29/2022
        ///5/13/2022
        ///5/27/2022
        ///6/10/2022
        ///6/24/2022
        ///7/8/2022
        ///7/22/2022
        ///8/5/2022
        ///8/19/2022
        ///9/2/2022
        ///9/16/2022
        ///9/30/2022
        ///10/14/2022
        ///10/28/2022
        ///11/11/2022
        ///11/25/2022
        ///12/9/2022
        ///12/23/2022
        ///1/6/2023
        ///1/20/2023
        ///2/3/2023
        ///2/17/2023
        ///3/3/2023
        ///3/17/2023
        ///3/31/2023
        ///4/14/2023
        ///4/28/2023
        ///5/12/2023
        ///5/26/2023
        ///6/9/2023
        ///6/23/2023
        ///7/7/2023
        ///7/21/2023
        ///8/4/2023
        ///8/18/2023
        ///9/1/2023
        ///9/15/2023
        ///9/29/2023
        ///10/13/2023
        ///10/27/2023
        ///11/10/2023
        ///11/24/2023 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string paydates {
            get {
                return ResourceManager.GetString("paydates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA - 100.04
        ///ABS PA - 109.79
        ///Library Aide (PT) - 119.60
        ///Library Aide (FT) - 128.80
        ///FT PA - 128.80
        ///Clerical Aide 6 HR - 83.94
        ///Clerical Aide 6.5 HR - 90.94
        ///Clerical Aide 4 HR - 55.96
        ///Health Aide FT - 106.05
        ///Health Aide 6 HR - 90.90
        ///Health Aide 5 HR - 75.75.
        /// </summary>
        internal static string payrates {
            get {
                return ResourceManager.GetString("payrates", resourceCulture);
            }
        }
    }
}
